### ISSUE TITLE
FEAT: Email notification option

### ISSUE THREAD

**Issue by interbiznw** [Monitorr/Monitorr#209] opened 2019-08-01 20:19 UTC
Setting to allow configuration of an external SMTP server to send email notifications when service is down. Also could expand to allow push notifications via slack or discord

**Comment by seanvree** [comment] 2019-12-21 08:37
@interbiznw  this is a dupe of https://github.com/Monitorr/Monitorr/issues/126 . 

It's in the works.

**Closed by seanvree** 2019-12-21 08:37 UTC
