### ISSUE TITLE
Uptime is not working (Shows 00:00:00:00)

### ISSUE THREAD

**Issue by Nomelas** [Monitorr/Monitorr#71] opened 2017-11-08 21:17 UTC
Server Specs:
Windowns 10 - Version 1703 (OS Build 15063.674)
nginx version 1.13.6
PHP version 7.1.11

PHP block in nginx.conf:

> 		## Enable PHP
>         location ~ \.php$ {
> 			try_files $uri =404;
> 			fastcgi_param HTTPS on;
>             fastcgi_pass 127.0.0.1:9000;
>             fastcgi_index index.php;
>             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
> 			fastcgi_param REMOTE_ADDR $http_x_real_ip;
>             include fastcgi_params;
> 		}

**Comment by seanvree** [comment] 2017-11-08 21:47
Received.  

Possibly related to https://github.com/Monitorr/Monitorr/issues/67

**Comment by seanvree** [comment] 2017-11-11 02:21
Notes: @wjbeckett 


Notice: A non well formed numeric value encountered in C:\inetpub\wwwroot\Monitorr\assets\php\functions.php on line 176

Notice: A non well formed numeric value encountered in C:\inetpub\wwwroot\Monitorr\assets\php\functions.php on line 178

Notice: A non well formed numeric value encountered in C:\inetpub\wwwroot\Monitorr\assets\php\functions.php on line 180

Notice: A non well formed numeric value encountered in C:\inetpub\wwwroot\Monitorr\assets\php\functions.php on line 182

**Comment by seanvree** [comment] 2017-11-11 23:02
Status: Bug identified.

Cause:  Script runs a linux command. If you have a linux subsystem installed in windows (ie MSYS2) then the uptime will be reported because the command will be valid. 

Working a resolution.

**Comment by seanvree** [comment] 2018-01-01 16:09
quick workaround is installing MSYS2 on the box or a similar linux subsystem so that PHP can run the Linux uptime command

**Comment by seanvree** [comment] 2018-01-10 11:04
Found a solution, just need to convert this time to H:M:s

```
<?php


$uptimeData = shell_exec('systeminfo | find "Time:"');
  
echo "<uptime>$uptimeData</uptime>\n";


```

**Comment by seanvree** [comment] 2018-01-10 12:00
Notes - The problem is converting the Windows reported TIME to the PHP time. 

```
<?php


$uptimeData = shell_exec('systeminfo | find "Time:"');
$currenttime = shell_exec('time /T');
$currentdate = shell_exec('date /T');



//Convert them to timestamps.
$date1Timestamp = strtotime($uptimeData);
$date2Timestamp = strtotime($currenttime);
 
//Calculate the difference.



//Seconds Diff:

$secondsdifference = $date2Timestamp - $date1Timestamp;
 

//DAYS Diff:

//Our "then" date.
$then = $uptimeData;
 
//Convert it into a timestamp.
$then = strtotime($then);
 
//Get the current timestamp.
$now = shell_exec('time /T');
 
//Calculate the difference.
$differencehourse = $now - $then;
 
//Convert seconds into days.
$days = floor($differencehours / (60*60*24) );




  
echo "<uptime> $uptimeData </uptime>\n";
echo "<br>\n";
echo "<currenttime>Current Time: $currentdate $currenttime </currenttime>\n";
echo "<br>\n";
echo "<differencetime>Seconds Difference: $secondsdifference </differencetime>\n";
echo "<br>\n";
echo "<differenceHours>Hours Difference: $differencehourse </differenceHours>\n";
echo "<br>\n";
echo "<differenceDays>Days Difference: $days </differenceDays>\n";


echo "<br>\n";
echo "<br>\n";


$then = '1/9/2018, 6:12:31 AM';
$then = new DateTime($then);
 
$now = new DateTime();
 
$sinceThen = $then->diff($now);
 
//Combined
echo $sinceThen->y.' years have passed.<br>';
echo $sinceThen->m.' months have passed.<br>';
echo $sinceThen->d.' days have passed.<br>';
echo $sinceThen->h.' hours have passed.<br>';
echo $sinceThen->i.' minutes have passed.<br>';

```

**Comment by seanvree** [comment] 2018-01-11 06:24
https://www.epochconverter.com/programming/php

**Comment by seanvree** [comment] 2018-01-18 03:38
@Nomelas I"m not sure if you're still having this problem, but I think I found the issue. 

In your PHP.ini file, can you check the setting that is below:
```
;auto_detect_line_endings = on
```
Try uncommenting out that line and set to ON if it's OFF.

Let me know.

**Comment by Nomelas** [comment] 2018-01-18 13:50
@seanvree changed that line. now the RAM shows 'NAN%' and uptime still isnt working

**Comment by seanvree** [comment] 2018-01-18 15:09
@Nomelas  okay, change that back.  

Also, what version does it say at the bottom of your Monitorr UI?

**Comment by seanvree** [comment] 2018-01-18 15:16
also, @Nomelas  you said you're running on NGINX inside of a windows VM, right?

**Comment by Nomelas** [comment] 2018-01-18 18:49
Repo: Monitorr // Version: v0.12.3d

no VMs, its just windows 10 lol

**Comment by seanvree** [comment] 2018-01-18 19:27
@Nomelas the ram problem was verified and fixed with this:

https://github.com/Monitorr/Monitorr/issues/67

However, since all your stats are wrong, I assume it's PHP.

Can you check these lines in your php.ini file:

make sure your php.ini file's include_path entry contains "."
make sure your php.ini has safe_mode set to 'off'.

**Comment by Nomelas** [comment] 2018-01-18 21:17
the cpu and ram stats are fine until I change the line that you specified:
;auto_detect_line_endings = on

changing it back sets them back to the correct values.

**Comment by seanvree** [comment] 2018-01-18 21:45
okay, so only uptime is not working then, yeah?

**Comment by Nomelas** [comment] 2018-01-18 21:51
Yes XD

**Comment by seanvree** [comment] 2018-01-18 22:15
got it. Thanks.

**Comment by seanvree** [comment] 2018-01-28 06:37
@Nomelas  I think got a quick fix for you my man. 

Can you test something for me first? 

can you open a Windows CMD Shell prompt and type "CUT" ?

should look like this:

```
Microsoft Windows [Version 10.0.17074.1002]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\seanvree.VREEDELL13>cut
cut: you must specify a list of bytes, characters, or fields
Try 'cut --help' for more information.

C:\Users\seanvree.VREEDELL13>
```

I assume you're going to get a response back like "no command exists?"

If you DO get a response like the one I pasted above, can you then run the following command:

```
cut -d. -f1 /proc/uptime
```

Let me know what your results are.

Thanks!

**Comment by Nomelas** [comment] 2018-01-29 03:03
'cut' is not recognized as an internal or external command,
operable program or batch file.

**Comment by seanvree** [comment] 2018-01-29 10:30
@Nomelas  yup, that's what I thought.  Would you be willing to download GIT on your bot from here:

https://git-scm.com/download/win

There's an important step you have to change the default values, it's on the 3rd step, looks like this:




![picture1](https://user-images.githubusercontent.com/8906637/35505893-5e74ce7e-049c-11e8-9dc7-017bd30ca632.png)

After you install it, then run "CUT" again.

**Comment by Nomelas** [comment] 2018-01-30 01:36
cut -d. -f1 /proc/uptime

^ this works now, but the latest version of Monitorr broke my entire Organizr setup.... had to remove it for now so I cant test it

**Comment by seanvree** [comment] 2018-01-30 01:42
@Nomelas  soooo...what happens when you access monitorr outside of Organizr?  ie localhost/organizr?  

Monitorr is just a website..it can't "break" another website.  However, if monitorr is not set up correctly, and you put it into organzir as an iframe, then yes, org will fail to load.

**Comment by seanvree** [comment] 2018-01-30 08:04
Closing issue.  Git must be added as a dependency if running on windows.

**Closed by seanvree** 2018-01-30 08:04 UTC
Labels: In Development, Priority: HIGH, Test: Pending, WiKi, bug

**Comment by Nomelas** [comment] 2018-02-01 01:12
still not working!

**Comment by Nomelas** [comment] 2018-02-01 01:13
@seanvree

**Comment by Nomelas** [comment] 2018-02-01 13:01
C:\nginx>cut -d. -f1 /proc/uptime
1835

**Comment by Nomelas** [comment] 2018-02-01 13:02
Oh, after a reboot, it started working:

uptime	00:00:31

**Comment by seanvree** [comment] 2018-02-01 13:27
@Nomelas  Heeyooooo.  The good 'ol "turn it off and back on again" trick eh?

Good to hear man.  Really appreciate your help testing, you gave us some insight into a huuuuge bug I've been trying to track down since we launched.  

Cheers.
